### ISSUE TITLE
Bug when loading over worldedit schematica

### ISSUE THREAD

**Issue by ChrisWesterfield** [rebane2001/mapartcraft#75]
Hi,
just wanted to load an map onto my server and paste it using world edit schematica.
I get this error:

[00:16:23] [WorldEdit Task Executor - 0/ERROR]: Uncaught exception occurred in task: Loading schematic druidtank.schem
java.io.IOException: Tag 'Schematic' does not exist or is not first
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.getBaseTag(SpongeSchematicReader.java:143) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:91) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:303) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:285) ~[?:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:139) ~[?:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[patched_1.15.2.jar:git-Paper-353]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[patched_1.15.2.jar:git-Paper-353]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[patched_1.15.2.jar:git-Paper-353]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

it seems that the schematic file seems to have an issue.
Do you have any suggestions how I can load the maps.

thanks

Chris

**Comment by rebane2001** [comment]
Worldedit does not support nbt schematics. I recommend using map.dat files if you are the server admin.
